version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_shopquanao
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nhaiduong91002
      MYSQL_DATABASE: shopquanao
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_shopquanao
    restart: always
    command: ["redis-server", "--requirepass", "nhaiduong91002"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    depends_on:
      - mysql

  shopquanao:
     build: .
     container_name: shopquanao_app
     restart: always
     depends_on:
       - mysql
       - redis
     environment:
       SPRING_PROFILES_ACTIVE: dev
       SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shopquanao?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
       SPRING_DATASOURCE_USERNAME: root
       SPRING_DATASOURCE_PASSWORD: nhaiduong91002
       SPRING_REDIS_HOST: redis
       SPRING_REDIS_PORT: 6379
       SPRING_REDIS_PASSWORD: nhaiduong91002
       SPRING_DEVTOOLS_RESTART_ENABLED: "true"
       SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "true"
     ports:
       - "8080:8080"
     working_dir: /app
     networks:
       - app_network
     volumes:
       - .:/app
       - ~/.m2:/root/.m2
     command: mvn spring-boot:run

volumes:
  mysql_data:
  redis_data:

networks:
  app_network:
