server:
  port: 8080
  tomcat:
    relaxed-path-chars: '<,>,[,\,],^,,{,|,},:'
    relaxed-query-chars: '<,>,[,\,],^,,{,|,},:'

spring:
  application:
    name: shopquanao

  datasource:
    url: jdbc:mysql://mysql:3306/shopquanao?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: nhaiduong91002
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "hibernate.dialect.storage_engine": innodb

  devtools:
    restart:
      enabled: true
    livereload:
      enable: true
    remote:
      enabled: true
   
  data:
    redis:
      host: redis_shopquanao
      port: 6379
      password: nhaiduong91002
      timeout: 60000

  mail:
    host: smtp.gmail.com
    port: 587
    username: haiduong09876@gmail.com
    password: jnekvfhqhvbucsph
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

app:
  fe: http://localhost:3000
  domain: http://localhost:8080
